export CUDA_VISIBLE_DEVICES=1,2,3,4,5,6

# nohup python difusco/train.py --task tsp --storage_path ./wo_softlen/ --diffusion_type categorical --sparse_factor -1 --auto_generate --auto_num_nodes 100 --auto_num_train 100000 --auto_num_val 1000 --auto_num_test 1000 --auto_two_opt_iterations 0 --do_train --pref_rl --resume_weight_only --ckpt_path ./checkpoints/tsp100_categorical.ckpt --num_epochs 10 --inference_diffusion_steps 50 --pref_num_start_nodes 8 --pref_pairs_per_graph 2 --wandb_logger_name PbDifusco_TSP_Categorical_Pref_RL --wandb_offline --batch_size 32 --pref_anchor_type l2sp --pref_anchor_weight 1e-3 --pref_freeze_bottom_layers 8 --learning_rate 5e-5 --pref_softlen_weight 0.0 --pref_softlen_degree_lambda 0.0 --fp16 --train_decode_sampling --train_sampling_K 4 --use_activation_checkpoint > train_tsp_categorical_pref_rl_2.log 2>&1 &

nohup python difusco/train.py --task tsp --storage_path ./wo_softlen/ --diffusion_type categorical --sparse_factor -1 --auto_generate --auto_num_nodes 100 --auto_num_train 100000 --auto_num_val 1000 --auto_num_test 1000 --auto_two_opt_iterations 0 --do_train --pref_rl --resume_weight_only --ckpt_path ./checkpoints/tsp100_categorical.ckpt --num_epochs 10 --inference_diffusion_steps 100 --batch_size 32 --learning_rate 3e-5 --train_decode_sampling --train_sampling_K 8 --pref_num_start_nodes 8 --pref_pairs_per_graph 4 --pref_softlen_weight 0.0 --pref_softlen_degree_lambda 0.0 --pref_supervised_weight 0.0 --pref_rl_weight 1.0 --pref_beta 0.5 --pref_anchor_type l2sp --pref_anchor_weight 1e-3 --pref_freeze_bottom_layers 8 --wandb_offline --wandb_logger_name TSP100_Categorical_PrefRL_Stable --fp16 > train.log 2>&1 &

# --pref_softlen_weight 0.05 --pref_softlen_degree_lambda 0.1 --pref_decode_random_tiebreak --pref_decode_noise_scale 1e-2

# python difusco/train.py --task tsp --storage_path <path> --pref_rl --diffusion_type categorical --pref_source twoopt --pref_2opt_steps 4 --pref_pairs_per_graph 3 --pref_rl_weight 1.0

# nohup python difusco/train.py --task tsp --storage_path ./last_k/ --diffusion_type categorical --sparse_factor -1 --auto_generate --auto_num_nodes 100 --auto_num_train 100000 --auto_num_val 1000 --auto_num_test 1000 --auto_two_opt_iterations 0 --do_train --pref_rl --resume_weight_only --ckpt_path ./checkpoints/tsp100_categorical.ckpt --num_epochs 10 --inference_diffusion_steps 50 --pref_decode_random_tiebreak --pref_decode_noise_scale 1e-3 --pref_num_start_nodes 8 --pref_pairs_per_graph 1 --wandb_logger_name PbDifusco_TSP_Categorical_Pref_RL --wandb_offline --batch_size 32 --pref_anchor_type l2sp --pref_anchor_weight 1e-5 --pref_freeze_bottom_layers 6 --learning_rate 5e-5 --pref_softlen_weight 0.05 --pref_softlen_degree_lambda 0.1 --fp16 --pref_apply_last_k_only --pref_last_k_steps 2 --pref_softlen_apply_last_k_only --pref_softlen_last_k_steps 2 --use_activation_checkpoint > train_tsp_categorical_pref_rl_last_k.log 2>&1 &